### ISSUE TITLE
Smartlook multithreading issue - Crash with IllegalStateException on version 1.8.4

### ISSUE THREAD

**Issue by shiSHARK** [smartlook/smartlook-mobile-issue-tracker#102]
Platform
Android, versions 8, 9, 10, 11

Technology
native Kotlin

Smartlook SDK version
1.8.4-native, before that working properly with version 1.7.0

Summary
Out Crashlytics reports a lot of crashes on the client devices - around 40%.
Related issue - https://github.com/smartlook/smartlook-mobile-issue-tracker/issues/95

Relevant logs and/or screenshots

Fatal Exception: java.lang.IllegalStateException: Already resumed, but proposed with update Failure {mOutputData=Data {}}
at a.a.a.j.a(SourceFile:325)
at a.a.a.j.a(SourceFile:9)
at a.a.b.a.e.e.e.c$c$a.a(SourceFile:4)
at a.a.b.a.e.e.e.c$c$a.invoke(SourceFile:1)
at a.a.b.a.e.e.e.a$b$a.a(SourceFile:10)
at a.a.b.a.e.e.e.a$b$a.invoke(SourceFile:1)
at a.a.b.a.b.e.c$d.a(SourceFile:1)
at a.a.b.a.b.e.c$d.invoke(SourceFile:1)
at a.a.b.a.b.b$c.a(SourceFile:3)
at a.a.b.a.b.d.a$b$b.run(SourceFile:1)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:221)
at android.app.ActivityThread.main(ActivityThread.java:7542)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by OndrejSynakSL** [comment]
Hello @shiSHARK ,

this is fixed in the newest SDK version:

`implementation 'com.smartlook.recording:app:1.8.5-native'`
Please update the SDK.
