### ISSUE TITLE
JSONException on startup: JSONObject["writerHost"] not a string

### ISSUE THREAD

**Issue by hyxabrod** [smartlook/smartlook-mobile-issue-tracker#17]
**Platform**
Android

**Technology**
Native

**Smartlook SDK version**
1.5.3-native

**Summary**
App crashes on SplashScreen

**Steps to reproduce [optional]**
Just run the app, it crashes on my splash screen. Once I disable Smartlook it runs well.

**Relevant logs and/or screenshots**
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: org.json.JSONException: JSONObject["writerHost"] not a string.
        at org.json.b.getString(SourceFile:840)
        at b.b.a.a.e.d.c$a$a.c(SourceFile:6)
        at b.b.a.a.e.d.c$b.c(SourceFile:18)
        at b.b.a.a.e.d.c$b.a(SourceFile:3)
        at b.b.a.a.h.c$a.a(SourceFile:1)
        at b.b.a.a.e.d.c$b.b(SourceFile:1)
        at b.b.a.a.e.d.c$b.d(SourceFile:2)
        at b.b.a.a.e.b$c.b(SourceFile:1)
        at a.b.a.a.e.d.a$b$c.run(SourceFile:1)
```

**Comment by adamblack** [comment]
Hi @hyxabrod ,

could you share some code snippet with usage of the SDK? Also, please share with us i.e. first 10 chars of your API key so I can check your project as well. Thanks!

**Comment by hyxabrod** [comment]
hey @adamblack 
sure,
048f306659
`BuildConfig.SMARTLOOK_KEY?.let { Smartlook.setupAndStartRecording(it) }`

**Comment by hyxabrod** [comment]
@adamblack 
if i add `-keep class org.json.** { *; }` to the proguard rules then it works fine, but... it worked fine before, without this keep

**Comment by adamblack** [comment]
@hyxabrod Ahhh, thanks for info, we will add some new rules to our proguard to be sure it is not gonna happen in the future.

In your case, maybe some 3rd party lib added some other rule that somehow manipulated org.json.** ? -> But I am just guessing. :]

In case everything is ok for now, feel free to close the issue and as I mentioned, we will add rules too new version as well.

**Comment by hyxabrod** [comment]
@adamblack nope, we have no such changes in our rules.
Have you changed anything in  responses from your back end?

**Comment by hyxabrod** [comment]
this `Caused by: org.json.JSONException: JSONObject["writerHost"] not a string.` means that the library can not parse a response

**Comment by adamblack** [comment]
@hyxabrod I believe it was a combination of multiple things: I can see you have reached recording limit for your project and together with that rule it led to weird issue.

However we just deployed new version of BE service that handles writerHost. -> We found the cause for JSONException. I tested that few minutes ago and it should be ok. Thanks for reporting that!

**Comment by hyxabrod** [comment]
Thank you @adamblack! Good luck with the project !

**Comment by hyxabrod** [comment]
P.S. @adamblack may you provide me more details about the reached limit? what a pricing plan should my company choose to avoid this situation
