### ISSUE TITLE
Android app crash when Smartlook SDK is initizlized

### ISSUE THREAD

**Issue by drdla49** [smartlook/smartlook-mobile-issue-tracker#54]
**Platform**
Android

**Technology**
native

**Affected devices [optional]**
Emulator
Samsung Galaxy Note 10 lite

**Smartlook SDK version**
com.smartlook.recording:app:1.7.0-native

**Summary**
App crash immediately after I call Smartlook.setupAndStartRecording or Smartlook.setup
I think that it's because we use androidX. When you migrate SDK to androidX?
Or do you think that it's another problem?

**Relevant logs and/or screenshots**

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/AppCompatActivity;
        at a.b.a.a.e.i.b.b$d.c(SourceFile:1)
        at a.b.a.a.e.i.b.b$d.a(SourceFile:1)
        at a.b.a.a.e.i.b.b$q$a.invoke(SourceFile:5)
        at a.b.a.a.e.i.b.b$q$a.invoke(SourceFile:1)
        at a.b.a.a.k.v.a(SourceFile:2)
        at a.b.a.a.e.i.b.b$q.onActivityStarted(SourceFile:12)
        at android.app.Application.dispatchActivityStarted(Application.java:425)
        at android.app.Activity.dispatchActivityStarted(Activity.java:1260)
        at android.app.Activity.onStart(Activity.java:1747)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:535)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at cz.tangosw.core.activity.CoreActivity.onStart(CoreActivity.java:101)
        at cz.myapp.base.delegate.activity.DelegateActivity.onStart(DelegateActivity.kt:72)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
        at android.app.Activity.performStart(Activity.java:7986)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3677)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatActivity" on path: DexPathList[[zip file "/data/app/cz.myapp.eshop.debug-MqJuZN0v5-oCkjXeeG3Ziw==/base.apk"],nativeLibraryDirectories=[/data/app/cz.myapp.eshop.debug-MqJuZN0v5-oCkjXeeG3Ziw==/lib/arm64, /data/app/cz.myapp.eshop.debug-MqJuZN0v5-oCkjXeeG3Ziw==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at a.b.a.a.e.i.b.b$d.c(SourceFile:1) 
        at a.b.a.a.e.i.b.b$d.a(SourceFile:1) 
        at a.b.a.a.e.i.b.b$q$a.invoke(SourceFile:5) 
        at a.b.a.a.e.i.b.b$q$a.invoke(SourceFile:1) 
        at a.b.a.a.k.v.a(SourceFile:2) 
        at a.b.a.a.e.i.b.b$q.onActivityStarted(SourceFile:12) 
        at android.app.Application.dispatchActivityStarted(Application.java:425) 
        at android.app.Activity.dispatchActivityStarted(Activity.java:1260) 
        at android.app.Activity.onStart(Activity.java:1747) 
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:535) 
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210) 
        at cz.tangosw.core.activity.CoreActivity.onStart(CoreActivity.java:101) 
        at cz.myapp.base.delegate.activity.DelegateActivity.onStart(DelegateActivity.kt:72) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433) 
        at android.app.Activity.performStart(Activity.java:7986) 
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3677) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8167) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) 
```

**Comment by SenNeonoveNoci** [comment]
Hello @drdla49,

we would love to upgrade our library to android, but sadly cannot do that yed, because it would not be backwards compatible. With that said this should not be a problem, because there is a mapping from support to android.

Do you have Jetifier enabled?
`gradle.properties`:
```
android.useAndroidX=true
android.enableJetifier=true
```
[Stackoverflow](https://stackoverflow.com/questions/52033810/can-i-use-library-that-used-android-support-with-androidx-projects)

**Comment by drdla49** [comment]
All other libraries that we used in our project are migrated to androidX, because of this we have
'''
android.enableJetifier=false
'''
Support library is old and not updated. I think that most developers have androidX. We use many big libraries and all use andoridX.
Please upgrade to androidX too.
Thanks.

**Comment by SenNeonoveNoci** [comment]
@drdla49 We have major clients using support, but we definitely can release an androidx version of our library.
I'm gonna prepare a version for you today, and in the next release, we gonna support both.

Sorry for the issues.

**Comment by SenNeonoveNoci** [comment]
@drdla49 Feel free to use the androidx version of Smartlook SDK.
```
implementation 'com.smartlook.recording:app:1.7.0-native-x'
```
If there are any further issues feel free to contact us.
