### ISSUE TITLE
Type a.a.a.a.a is defined multiple times

### ISSUE THREAD

**Issue by bguedon** [smartlook/smartlook-mobile-issue-tracker#76]
**Platform**

Android

**Technology**

native

**Smartlook SDK version**

1.7.0

**Summary**

We have a third-party aar dependency in our project that contains same a.a.a.a.a obfuscated class as your sdk.
Is it possible for you to tell your obfuscator to move obfuscated classes to a dedicated package in order to avoid such conflicts ?
In proguard this is the -repackageclasses option

**Relevant logs and/or screenshots**

```
2021-04-14T09:32:52.338+0200 [ERROR] [com.android.build.gradle.internal.tasks.DexMergingTask] /Users/bruno/StudioProjects/free2move-unicorn/app-v2/build/intermediates/mixed_scope_dex_archive/unicornDebug/out/3adcc275b9f9be9625d450a4b48d82beaf7683b89c8297ba91adfc179717ee7e_1.jar: D8: Type a.a.a.a.a is defined multiple times: /Users/bruno/StudioProjects/free2move-unicorn/app-v2/build/intermediates/mixed_scope_dex_archive/unicornDebug/out/3adcc275b9f9be9625d450a4b48d82beaf7683b89c8297ba91adfc179717ee7e_1.jar:classes.dex, /Users/bruno/StudioProjects/free2move-unicorn/app-v2/build/intermediates/mixed_scope_dex_archive/unicornDebug/out/7f3b2fdf6dd0aa4b953db07a26a95e6a4af1423860d66a7d1b1424a4d4e3d9d8_1.jar:classes.dex
2021-04-14T09:32:52.339+0200 [ERROR] [com.android.build.gradle.internal.tasks.DexMergingTaskRunnable] com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Type a.a.a.a.a is defined multiple times: /Users/bruno/StudioProjects/free2move-unicorn/app-v2/build/intermediates/mixed_scope_dex_archive/unicornDebug/out/3adcc275b9f9be9625d450a4b48d82beaf7683b89c8297ba91adfc179717ee7e_1.jar:classes.dex, /Users/bruno/StudioProjects/free2move-unicorn/app-v2/build/intermediates/mixed_scope_dex_archive/unicornDebug/out/7f3b2fdf6dd0aa4b953db07a26a95e6a4af1423860d66a7d1b1424a4d4e3d9d8_1.jar:classes.dex
        at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:132)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:119)
        at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
        at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:432)
        at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:242)
        at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:57)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:67)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60)
        at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/bruno/StudioProjects/free2move-unicorn/app-v2/build/intermediates/mixed_scope_dex_archive/unicornDebug/out/3adcc275b9f9be9625d450a4b48d82beaf7683b89c8297ba91adfc179717ee7e_1.jar:classes.dex
        at Version.fakeStackEntry(Version_2.1.86.java:0)
        at com.android.tools.r8.utils.Y.a(SourceFile:78)
        at com.android.tools.r8.D8.run(D8.java:11)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:117)
        ... 33 more
Caused by: com.android.tools.r8.utils.b: Type a.a.a.a.a is defined multiple times: /Users/bruno/StudioProjects/free2move-unicorn/app-v2/build/intermediates/mixed_scope_dex_archive/unicornDebug/out/3adcc275b9f9be9625d450a4b48d82beaf7683b89c8297ba91adfc179717ee7e_1.jar:classes.dex, /Users/bruno/StudioProjects/free2move-unicorn/app-v2/build/intermediates/mixed_scope_dex_archive/unicornDebug/out/7f3b2fdf6dd0aa4b953db07a26a95e6a4af1423860d66a7d1b1424a4d4e3d9d8_1.jar:classes.dex
        at com.android.tools.r8.utils.T0.error(SourceFile:1)
        at com.android.tools.r8.utils.T0.a(SourceFile:2)
        at com.android.tools.r8.utils.R0.b(SourceFile:6)
        at com.android.tools.r8.utils.R0.a(SourceFile:24)
        at com.android.tools.r8.utils.R0.a(SourceFile:10)
        at java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:1990)
        at com.android.tools.r8.utils.R0.a(SourceFile:6)
        at com.android.tools.r8.graph.Q0$c.f(SourceFile:3)
        at com.android.tools.r8.dex.a.a(SourceFile:298)
        at com.android.tools.r8.dex.a.a(SourceFile:226)
        at com.android.tools.r8.D8.d(D8.java:6)
        at com.android.tools.r8.D8.b(D8.java:1)
        at com.android.tools.r8.utils.Y.a(SourceFile:36)
        ... 35 more

```

**Comment by adamblack** [comment]
Hi @bguedon ,

good catch! We will address this soon in next release.
