### ISSUE TITLE
Fatal Exception: com.facebook.react.bridge.NativeArgumentsParseException: RNSmartlook.setupAndStartRecording got 1 arguments, expected 2

### ISSUE THREAD

**Issue by githubbla** [smartlook/smartlook-mobile-issue-tracker#78]
**Platform**

Both
**Technology**

React native
**Build instructions [optional]**

**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**

0.31
**Summary**

i see only this issue with crashalitic, i unable to repeat

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**

Fatal Exception: com.facebook.react.bridge.NativeArgumentsParseException: RNSmartlook.setupAndStartRecording got 1 arguments, expected 2
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:795)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:166)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:780)

**Comment by githubbla** [comment]
may be it's mix between npm/pod 0.31 and 0.39

**Comment by adamblack** [comment]
Hi @githubbla ,

this seems to be very weird bug. Only scenario I can think of is that somehow gradle dependency was updated, but not npm lib itself. Otherwise this would not be possible.

However it is very old version so I am not sure we can do something about that at this point. In case there is any other issue, feel free to open new one.
