### ISSUE TITLE
App crashes after SDK install and setup

### ISSUE THREAD

**Issue by san-sk** [smartlook/smartlook-mobile-issue-tracker#87]
**Platform**

Android

**Technology**

native

**Build instructions [optional]**

**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**

1.8.1-native

**Summary**

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**

`E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.IllegalAccessError: Illegal class access: 'a.a.b.a.f.t.j' attempting to access 'com.google.android.material.tabs.TabLayout$TabView' (declaration of 'a.a.b.a.f.t.j' appears in /data/app/~~1c6v1Tl5Se7wOqNkuRB6oA==/com.test.test.debug-LoOg0jf1KIrhP4tpx7f6Ew==/base.apk!classes2.dex)
        at a.a.b.a.f.t.j.l(SourceFile:1)
        at a.a.b.a.f.o.m(SourceFile:2)
        at a.a.b.a.f.o.a(SourceFile:477)
        at a.a.b.a.a.b.c.b.a(SourceFile:45)
        at a.a.b.a.a.b.c.b.i(SourceFile:5)
        at a.a.b.a.a.b.c.a.d(SourceFile:280)
        at a.a.b.a.a.b.g.c.b.dispatchTouchEvent(SourceFile:1)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
        at android.view.View.dispatchPointerEvent(View.java:14568)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6027)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5825)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5316)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5491)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5548)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8091)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8042)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8003)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8214)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:7661)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

`

**Comment by san-sk** [comment]
If your app uses Material Design please update the version to 1.2.1 or later.
