### ISSUE TITLE
Smartlook multithreading issue - Crash with IllegalStateException on version 1.8.0 - 1.8.3

### ISSUE THREAD

**Issue by shiSHARK** [smartlook/smartlook-mobile-issue-tracker#95]
**Platform**
Android, versions 8, 9, 10, 11

**Technology**
native Kotlin

**Smartlook SDK version**
1.8.0, 1.8.3, before that working properly with version 1.7.0

**Summary**
Out Crashlytics reports a lot of crashes on the client devices - around 40%.

**Relevant logs and/or screenshots**

Fatal Exception: java.lang.IllegalStateException: Already resumed, but proposed with update Failure {mOutputData=Data {}}
       at a.a.a.j.a(SourceFile:325)
       at a.a.a.j.a(SourceFile:9)
       at a.a.b.a.e.e.e.c$c$a.a(SourceFile:4)
       at a.a.b.a.e.e.e.c$c$a.invoke(SourceFile:1)
       at a.a.b.a.e.e.e.a$b$a.a(SourceFile:10)
       at a.a.b.a.e.e.e.a$b$a.invoke(SourceFile:1)
       at a.a.b.a.b.e.c$d.a(SourceFile:1)
       at a.a.b.a.b.e.c$d.invoke(SourceFile:1)
       at a.a.b.a.b.b$c.a(SourceFile:3)
       at a.a.b.a.b.d.a$b$b.run(SourceFile:1)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)

and 

Fatal Exception: java.lang.IllegalStateException: Already resumed, but proposed with update Success {mOutputData=Data {}}
       at a.a.a.j.a(SourceFile:325)
       at a.a.a.j.a(SourceFile:9)
       at a.a.b.a.e.e.e.c$c$a.a(SourceFile:1)
       at a.a.b.a.e.e.e.c$c$a.invoke(SourceFile:1)
       at a.a.b.a.e.e.e.a$b$a.a(SourceFile:3)
       at a.a.b.a.e.e.e.a$b$a.invoke(SourceFile:1)
       at a.a.b.a.b.e.c$d.a(SourceFile:1)
       at a.a.b.a.b.e.c$d.invoke(SourceFile:1)
       at a.a.b.a.b.b$c.a(SourceFile:7)
       at a.a.b.a.b.d.a$b$c.run(SourceFile:1)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8587)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by SenNeonoveNoci** [comment]
Hello, @shiSHARK what version of android SDK are you using? We had reports on this issue but have fixed it in the newest version `implementation 'com.smartlook.recording:app:1.8.3-native'`.

**Comment by shiSHARK** [comment]
We use Android compile version 30, Java version 11, and I have deployed two version to our users with com.smartlook.recording:app:1.8.0-native and com.smartlook.recording:app:1.8.3-native and they both have the same issue in the crashlytics reports.

**Comment by SenNeonoveNoci** [comment]
Hello, @shiSHARK  all our issues should be fixed in the newest SDK version `1.8.4-native`.

**Comment by shiSHARK** [comment]
I would like to reopen this issue. I reproduce it with the latest version `1.8.4-native`

Here is the stacktrace:

Fatal Exception: java.lang.IllegalStateException: Already resumed, but proposed with update Failure {mOutputData=Data {}}
       at a.a.a.j.a(SourceFile:325)
       at a.a.a.j.a(SourceFile:9)
       at a.a.b.a.e.e.e.c$c$a.a(SourceFile:4)
       at a.a.b.a.e.e.e.c$c$a.invoke(SourceFile:1)
       at a.a.b.a.e.e.e.a$b$a.a(SourceFile:10)
       at a.a.b.a.e.e.e.a$b$a.invoke(SourceFile:1)
       at a.a.b.a.b.e.c$d.a(SourceFile:1)
       at a.a.b.a.b.e.c$d.invoke(SourceFile:1)
       at a.a.b.a.b.b$c.a(SourceFile:3)
       at a.a.b.a.b.d.a$b$b.run(SourceFile:1)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:221)
       at android.app.ActivityThread.main(ActivityThread.java:7542)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
